package org.brunoeleodoro.com.fatechorarios;

/**
 * Created by bruno on 16/02/17.
 */

public class Aulas_ADS {
    String curso = "";
    Aulas aulas = new Aulas();
    public Aulas_ADS(String curso)
    {
        this.curso = curso;
    }
    public String[] getA_segunda_1_m_aulas() {
        return new String[]{};
    }

    public String[] getA_terca_1_m_aulas() {String[] vetor = new String[]{};
        if(curso.equals("ADS 1º sem - Manhã")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("ADS 2º sem - Manhã")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("ADS 3º sem - Manhã")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("ADS 4º sem - Manhã")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("ADS 5º sem - Manhã")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("ADS 6º sem - Manhã")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("ADS 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}

        return vetor;
    }

    public String[] getA_quarta_1_m_aulas() {String[] vetor = new String[]{};
        if(curso.equals("ADS 1º sem - Manhã")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("ADS 2º sem - Manhã")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("ADS 3º sem - Manhã")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("ADS 4º sem - Manhã")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("ADS 5º sem - Manhã")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("ADS 6º sem - Manhã")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("ADS 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}

        return vetor;
    }

    public String[] getA_quinta_1_m_aulas() {
        String[] vetor = new String[]{};
        if(curso.equals("ADS 1º sem - Manhã")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("ADS 2º sem - Manhã")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("ADS 3º sem - Manhã")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("ADS 4º sem - Manhã")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("ADS 5º sem - Manhã")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("ADS 6º sem - Manhã")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("ADS 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}

        return vetor;
    }

    public String[] getA_sexta_1_m_aulas() {String[] vetor = new String[]{};
        if(curso.equals("ADS 1º sem - Manhã")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("ADS 2º sem - Manhã")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("ADS 3º sem - Manhã")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("ADS 4º sem - Manhã")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("ADS 5º sem - Manhã")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("ADS 6º sem - Manhã")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("ADS 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}

        return vetor;
    }

    public String[] getA_segunda_1_m_professores() {String[] vetor = new String[]{};
        if(curso.equals("ADS 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_professores;}
        else if(curso.equals("ADS 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_professores;}
        else if(curso.equals("ADS 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_professores;}
        else if(curso.equals("ADS 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_professores;}
        else if(curso.equals("ADS 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_professores;}
        else if(curso.equals("ADS 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_professores;}
        else if(curso.equals("ADS 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}

        return vetor;
    }

    public String[] getA_terca_1_m_professores() {
        String[] vetor = new String[]{};
        if(curso.equals("ADS 1º sem - Manhã")){vetor = aulas.a_terca_1_m_professores;}
        else if(curso.equals("ADS 2º sem - Manhã")){vetor = aulas.a_terca_1_m_professores;}
        else if(curso.equals("ADS 3º sem - Manhã")){vetor = aulas.a_terca_1_m_professores;}
        else if(curso.equals("ADS 4º sem - Manhã")){vetor = aulas.a_terca_1_m_professores;}
        else if(curso.equals("ADS 5º sem - Manhã")){vetor = aulas.a_terca_1_m_professores;}
        else if(curso.equals("ADS 6º sem - Manhã")){vetor = aulas.a_terca_1_m_professores;}
        else if(curso.equals("ADS 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}

        return vetor;
    }

    public String[] getA_quarta_1_m_professores() {
        String[] vetor = new String[]{};
        if(curso.equals("ADS 1º sem - Manhã")){vetor = aulas.a_quarta_1_m_professores;}
        else if(curso.equals("ADS 2º sem - Manhã")){vetor = aulas.a_quarta_1_m_professores;}
        else if(curso.equals("ADS 3º sem - Manhã")){vetor = aulas.a_quarta_1_m_professores;}
        else if(curso.equals("ADS 4º sem - Manhã")){vetor = aulas.a_quarta_1_m_professores;}
        else if(curso.equals("ADS 5º sem - Manhã")){vetor = aulas.a_quarta_1_m_professores;}
        else if(curso.equals("ADS 6º sem - Manhã")){vetor = aulas.a_quarta_1_m_professores;}
        else if(curso.equals("ADS 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}

        return vetor;
    }

    public String[] getA_quinta_1_m_professores() {
        String[] vetor = new String[]{};
        if(curso.equals("ADS 1º sem - Manhã")){vetor = aulas.a_quinta_1_m_professores;}
        else if(curso.equals("ADS 2º sem - Manhã")){vetor = aulas.a_quinta_1_m_professores;}
        else if(curso.equals("ADS 3º sem - Manhã")){vetor = aulas.a_quinta_1_m_professores;}
        else if(curso.equals("ADS 4º sem - Manhã")){vetor = aulas.a_quinta_1_m_professores;}
        else if(curso.equals("ADS 5º sem - Manhã")){vetor = aulas.a_quinta_1_m_professores;}
        else if(curso.equals("ADS 6º sem - Manhã")){vetor = aulas.a_quinta_1_m_professores;}
        else if(curso.equals("ADS 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}

        return vetor;
    }

    public String[] getA_sexta_1_m_professores() {
        String[] vetor = new String[]{};
        if(curso.equals("ADS 1º sem - Manhã")){vetor = aulas.a_sexta_1_m_professores;}
        else if(curso.equals("ADS 2º sem - Manhã")){vetor = aulas.a_sexta_1_m_professores;}
        else if(curso.equals("ADS 3º sem - Manhã")){vetor = aulas.a_sexta_1_m_professores;}
        else if(curso.equals("ADS 4º sem - Manhã")){vetor = aulas.a_sexta_1_m_professores;}
        else if(curso.equals("ADS 5º sem - Manhã")){vetor = aulas.a_sexta_1_m_professores;}
        else if(curso.equals("ADS 6º sem - Manhã")){vetor = aulas.a_sexta_1_m_professores;}
        else if(curso.equals("ADS 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}

        return vetor;
    }





    public String[] getA_segunda_1_m_horarios() {
        String[] vetor = new String[]{};
        if(curso.equals("ADS 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_horarios;}
        else if(curso.equals("ADS 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_horarios;}
        else if(curso.equals("ADS 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_horarios;}
        else if(curso.equals("ADS 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_horarios;}
        else if(curso.equals("ADS 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_horarios;}
        else if(curso.equals("ADS 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_horarios;}
        else if(curso.equals("ADS 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("ADS 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Vespertino")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 1º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 2º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 3º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 4º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 5º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 6º sem - Manhã")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Segurança da informação 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 1º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 2º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 3º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 4º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 5º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}
        else if(curso.equals("Textil 6º sem - Noturno")){vetor = aulas.a_segunda_1_m_aulas;}

        return vetor;
    }

    public String[] getA_terca_1_m_horarios() {
        String[] vetor = new String[]{};
        if(curso.equals("ADS 1º sem - Manhã")){vetor = aulas.a_terca_1_m_horarios;}
        else if(curso.equals("ADS 2º sem - Manhã")){vetor = aulas.a_terca_1_m_horarios;}
        else if(curso.equals("ADS 3º sem - Manhã")){vetor = aulas.a_terca_1_m_horarios;}
        else if(curso.equals("ADS 4º sem - Manhã")){vetor = aulas.a_terca_1_m_horarios;}
        else if(curso.equals("ADS 5º sem - Manhã")){vetor = aulas.a_terca_1_m_horarios;}
        else if(curso.equals("ADS 6º sem - Manhã")){vetor = aulas.a_terca_1_m_horarios;}
        else if(curso.equals("ADS 1º sem - Vespertino")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("ADS 2º sem - Vespertino")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("ADS 3º sem - Vespertino")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("ADS 4º sem - Vespertino")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("ADS 5º sem - Vespertino")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("ADS 6º sem - Vespertino")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 1º sem - Manhã")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 2º sem - Manhã")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 3º sem - Manhã")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 4º sem - Manhã")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 5º sem - Manhã")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 6º sem - Manhã")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 1º sem - Vespertino")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 2º sem - Vespertino")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 3º sem - Vespertino")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 4º sem - Vespertino")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 5º sem - Vespertino")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 6º sem - Vespertino")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 1º sem - Noturno")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 2º sem - Noturno")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 3º sem - Noturno")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 4º sem - Noturno")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 5º sem - Noturno")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 6º sem - Noturno")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Manhã")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Manhã")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Manhã")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Manhã")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Manhã")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Manhã")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Vespertino")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Vespertino")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Vespertino")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Vespertino")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Vespertino")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Vespertino")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Noturno")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Noturno")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Noturno")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Noturno")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Noturno")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Noturno")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Segurança da informação 1º sem - Manhã")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Segurança da informação 2º sem - Manhã")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Segurança da informação 3º sem - Manhã")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Segurança da informação 4º sem - Manhã")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Segurança da informação 5º sem - Manhã")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Segurança da informação 6º sem - Manhã")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Segurança da informação 1º sem - Noturno")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Segurança da informação 2º sem - Noturno")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Segurança da informação 3º sem - Noturno")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Segurança da informação 4º sem - Noturno")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Segurança da informação 5º sem - Noturno")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Segurança da informação 6º sem - Noturno")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Textil 1º sem - Noturno")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Textil 2º sem - Noturno")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Textil 3º sem - Noturno")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Textil 4º sem - Noturno")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Textil 5º sem - Noturno")){vetor = aulas.a_terca_1_m_aulas;}
        else if(curso.equals("Textil 6º sem - Noturno")){vetor = aulas.a_terca_1_m_aulas;}

        return vetor;
    }

    public String[] getA_quarta_1_m_horarios() {
        String[] vetor = new String[]{};
        if(curso.equals("ADS 1º sem - Manhã")){vetor = aulas.a_quarta_1_m_horarios;}
        else if(curso.equals("ADS 2º sem - Manhã")){vetor = aulas.a_quarta_1_m_horarios;}
        else if(curso.equals("ADS 3º sem - Manhã")){vetor = aulas.a_quarta_1_m_horarios;}
        else if(curso.equals("ADS 4º sem - Manhã")){vetor = aulas.a_quarta_1_m_horarios;}
        else if(curso.equals("ADS 5º sem - Manhã")){vetor = aulas.a_quarta_1_m_horarios;}
        else if(curso.equals("ADS 6º sem - Manhã")){vetor = aulas.a_quarta_1_m_horarios;}
        else if(curso.equals("ADS 1º sem - Vespertino")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("ADS 2º sem - Vespertino")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("ADS 3º sem - Vespertino")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("ADS 4º sem - Vespertino")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("ADS 5º sem - Vespertino")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("ADS 6º sem - Vespertino")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 1º sem - Manhã")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 2º sem - Manhã")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 3º sem - Manhã")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 4º sem - Manhã")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 5º sem - Manhã")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 6º sem - Manhã")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 1º sem - Vespertino")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 2º sem - Vespertino")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 3º sem - Vespertino")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 4º sem - Vespertino")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 5º sem - Vespertino")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 6º sem - Vespertino")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 1º sem - Noturno")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 2º sem - Noturno")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 3º sem - Noturno")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 4º sem - Noturno")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 5º sem - Noturno")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 6º sem - Noturno")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Manhã")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Manhã")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Manhã")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Manhã")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Manhã")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Manhã")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Vespertino")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Vespertino")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Vespertino")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Vespertino")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Vespertino")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Vespertino")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Noturno")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Noturno")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Noturno")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Noturno")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Noturno")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Noturno")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 1º sem - Manhã")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 2º sem - Manhã")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 3º sem - Manhã")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 4º sem - Manhã")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 5º sem - Manhã")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 6º sem - Manhã")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 1º sem - Noturno")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 2º sem - Noturno")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 3º sem - Noturno")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 4º sem - Noturno")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 5º sem - Noturno")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 6º sem - Noturno")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Textil 1º sem - Noturno")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Textil 2º sem - Noturno")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Textil 3º sem - Noturno")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Textil 4º sem - Noturno")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Textil 5º sem - Noturno")){vetor = aulas.a_quarta_1_m_aulas;}
        else if(curso.equals("Textil 6º sem - Noturno")){vetor = aulas.a_quarta_1_m_aulas;}

        return vetor;
    }

    public String[] getA_quinta_1_m_horarios() {
        String[] vetor = new String[]{};
        if(curso.equals("ADS 1º sem - Manhã")){vetor = aulas.a_quinta_1_m_horarios;}
        else if(curso.equals("ADS 2º sem - Manhã")){vetor = aulas.a_quinta_1_m_horarios;}
        else if(curso.equals("ADS 3º sem - Manhã")){vetor = aulas.a_quinta_1_m_horarios;}
        else if(curso.equals("ADS 4º sem - Manhã")){vetor = aulas.a_quinta_1_m_horarios;}
        else if(curso.equals("ADS 5º sem - Manhã")){vetor = aulas.a_quinta_1_m_horarios;}
        else if(curso.equals("ADS 6º sem - Manhã")){vetor = aulas.a_quinta_1_m_horarios;}
        else if(curso.equals("ADS 1º sem - Vespertino")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("ADS 2º sem - Vespertino")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("ADS 3º sem - Vespertino")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("ADS 4º sem - Vespertino")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("ADS 5º sem - Vespertino")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("ADS 6º sem - Vespertino")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 1º sem - Manhã")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 2º sem - Manhã")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 3º sem - Manhã")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 4º sem - Manhã")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 5º sem - Manhã")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 6º sem - Manhã")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 1º sem - Vespertino")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 2º sem - Vespertino")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 3º sem - Vespertino")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 4º sem - Vespertino")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 5º sem - Vespertino")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 6º sem - Vespertino")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 1º sem - Noturno")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 2º sem - Noturno")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 3º sem - Noturno")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 4º sem - Noturno")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 5º sem - Noturno")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 6º sem - Noturno")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Manhã")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Manhã")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Manhã")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Manhã")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Manhã")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Manhã")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Vespertino")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Vespertino")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Vespertino")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Vespertino")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Vespertino")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Vespertino")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Noturno")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Noturno")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Noturno")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Noturno")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Noturno")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Noturno")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 1º sem - Manhã")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 2º sem - Manhã")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 3º sem - Manhã")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 4º sem - Manhã")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 5º sem - Manhã")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 6º sem - Manhã")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 1º sem - Noturno")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 2º sem - Noturno")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 3º sem - Noturno")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 4º sem - Noturno")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 5º sem - Noturno")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 6º sem - Noturno")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Textil 1º sem - Noturno")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Textil 2º sem - Noturno")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Textil 3º sem - Noturno")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Textil 4º sem - Noturno")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Textil 5º sem - Noturno")){vetor = aulas.a_quinta_1_m_aulas;}
        else if(curso.equals("Textil 6º sem - Noturno")){vetor = aulas.a_quinta_1_m_aulas;}

        return vetor;
    }

    public String[] getA_sexta_1_m_horarios() {
        String[] vetor = new String[]{};
        if(curso.equals("ADS 1º sem - Manhã")){vetor = aulas.a_sexta_1_m_horarios;}
        else if(curso.equals("ADS 2º sem - Manhã")){vetor = aulas.a_sexta_1_m_horarios;}
        else if(curso.equals("ADS 3º sem - Manhã")){vetor = aulas.a_sexta_1_m_horarios;}
        else if(curso.equals("ADS 4º sem - Manhã")){vetor = aulas.a_sexta_1_m_horarios;}
        else if(curso.equals("ADS 5º sem - Manhã")){vetor = aulas.a_sexta_1_m_horarios;}
        else if(curso.equals("ADS 6º sem - Manhã")){vetor = aulas.a_sexta_1_m_horarios;}
        else if(curso.equals("ADS 1º sem - Vespertino")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("ADS 2º sem - Vespertino")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("ADS 3º sem - Vespertino")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("ADS 4º sem - Vespertino")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("ADS 5º sem - Vespertino")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("ADS 6º sem - Vespertino")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 1º sem - Manhã")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 2º sem - Manhã")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 3º sem - Manhã")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 4º sem - Manhã")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 5º sem - Manhã")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 6º sem - Manhã")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 1º sem - Vespertino")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 2º sem - Vespertino")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 3º sem - Vespertino")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 4º sem - Vespertino")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 5º sem - Vespertino")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Gestão Empresarial 6º sem - Vespertino")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 1º sem - Noturno")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 2º sem - Noturno")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 3º sem - Noturno")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 4º sem - Noturno")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 5º sem - Noturno")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Jogos Digitais 6º sem - Noturno")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Manhã")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Manhã")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Manhã")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Manhã")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Manhã")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Manhã")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Vespertino")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Vespertino")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Vespertino")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Vespertino")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Vespertino")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Vespertino")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Logistica 1º sem - Noturno")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Logistica 2º sem - Noturno")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Logistica 3º sem - Noturno")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Logistica 4º sem - Noturno")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Logistica 5º sem - Noturno")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Logistica 6º sem - Noturno")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 1º sem - Manhã")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 2º sem - Manhã")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 3º sem - Manhã")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 4º sem - Manhã")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 5º sem - Manhã")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 6º sem - Manhã")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 1º sem - Noturno")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 2º sem - Noturno")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 3º sem - Noturno")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 4º sem - Noturno")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 5º sem - Noturno")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Segurança da informação 6º sem - Noturno")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Textil 1º sem - Noturno")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Textil 2º sem - Noturno")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Textil 3º sem - Noturno")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Textil 4º sem - Noturno")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Textil 5º sem - Noturno")){vetor = aulas.a_sexta_1_m_aulas;}
        else if(curso.equals("Textil 6º sem - Noturno")){vetor = aulas.a_sexta_1_m_aulas;}

        return vetor;
    }
}
